# Recognitions
- award: Introduction to Kubernetes
  organization: SysOps Polska
  year: 2024

- award: Cisco CCNA Routing and Switching - Introduction to networks
  organization: Cisco
  year: 2018

- award: Cambridge English ESOL International First B2
  organization: Cambridge English
  year: 2014
